### ISSUE TITLE
Fixing code with Numpy2.0 and Scipy

### ISSUE THREAD

**Issue by bosby74** [gzenhaeusern/polarisation-package#2]
Dear,
 another issue about your python code v0.1. 
With the introduction of Numpy2.0 some of the commands in your original script don't run properly.
For example:
- in Numpy2.0, np.infty is deprecated and np.inf should be use
- in Scipy 1.14, signal.hanning is deprecated and signal.windows.hann should be use

just to keep inform you about changes I have to do in my scripts to run...

Simone

**Comment by gzenhaeusern** [comment]
Thank you for the comment! Unfortunately I do not have the time to keep the code updated to the latest versions of packages. I'm glad you found an easy solution to the errors.
